### ISSUE TITLE
File Not found error

### ISSUE THREAD

**Issue by GOKULNATH-RS** [ASTROs-TEAM/SNAP_SYNC#2]
```
Error: Command failed: python index2.py checkImg/gokul_1.png6e43764d-6f16-4104-896a-a0b6c2f0f21a 6663d7c4fa12ab796389c0a0/
Traceback (most recent call last):
  File "D:\Projects\chore\SNAP_SYNC\server\index2.py", line 13, in <module>
    cred = credentials.Certificate("./firebase-cred.json")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GOKULNATH RS\AppData\Local\Programs\Python\Python311\Lib\site-packages\firebase_admin\credentials.py", line 83, in __init__
    with open(cert) as json_file:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './firebase-cred.json'

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)  
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python index2.py checkImg/gokul_1.png6e43764d-6f16-4104-896a-a0b6c2f0f21a 6663d7c4fa12ab796389c0a0/'      
}

```

File not found error

I think we should create a new firebase project , may be the old one got expired

**Comment by GOKULNATH-RS** [comment]
it will affect deployment
